---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
  namespace: elves
spec:
  replicas: 3
  selector:
    matchLabels:
      run: gateway
      app: gateway
  template:
    metadata:
      labels:
        run: gateway
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "cloudelves/gateway:TAG"
          imagePullPolicy: Always
          env:
          # - name: registry.serviceName
          #   value: REGISTRY_SERVICE
          - name: server.port
            value: "8080"
          - name: rmq.host
            value: "149.165.155.17"
          - name: rmq.port
            value: "30006"
          - name: ingestor.host
            value: "149.165.155.17"
          - name: ingestor.port
            value: "30002"
          - name: registry.host
            value: "149.165.155.17"
          - name: registry.port
            value: "30001"

          ports:
          - name: gateway
            containerPort: 8080
            protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: elves
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30005

