kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
  namespace: elves
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gateway
      app: gateway
  template:
    metadata:
      labels:
        run: gateway
        app: gateway
    spec:
      containers:
      - name: gateway
        image: "cloudelves/gateway:TAG"
        imagePullPolicy: Always
        ports:
        - name: gateway
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: elves
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30021