apiVersion: v1
kind: Service
metadata:
  name: ingestor-service
spec:
  selector:
    app: ingestor
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30002