kind: Deployment
apiVersion: apps/v1
metadata:
  name: ingestor
  namespace: elves
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingestor
      app: ingestor
  template:
    metadata:
      labels:
        run: ingestor
        app: ingestor
    spec:
      containers:
        - name: ingestor
          image: docker.io/madhavankr/elves-ingestor:latest
          imagePullPolicy: Always
          env:
          - name: rmq_service_name
            value: RABBITMQ_SERVICE
          - name: rmq_host
            value: mu-rabbit-rabbitmq.elves.svc
          - name: rmq_port
            value: "5672"
          - name: rmq_user
            value: "guest"
          - name: rmq_password
            value: "guest"
          ports:
          - name: ingestor
            containerPort: 8080
            protocol: TCP

