pipeline {
    agent any

    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }
    environment {
        imagename = "cloudelves/registry"
        dockerImage = ''
    }
    stages {
        stage('Cleanup') {
            steps {
                // Clean before build
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                echo "Checking out 'ci/registry' branch"
                git branch: 'HW3/registry',
                url: 'https://github.com/airavata-courses/CloudElves.git',
                credentialsId: 'MyGitHub'
            }
        }
        stage('Build Docker Image') {
             steps {
                dir('registry') {
                    sh 'pwd'
                    sh './mvnw clean package -Dmaven.test.skip'
                    script {
                        dockerImage = docker.build imagename
                    }
                }
            }
        }
         stage('Publish to DockerHub') {
            environment {
                registryCredential = 'dockerHub'
            }
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }
        stage('Remove unused docker image') {
            steps{
                sh "docker rmi $imagename:$BUILD_NUMBER"
                sh "docker rmi $imagename:latest"

            }
        }
        stage('Checkout ansible deployments branch') {
            steps {
                echo "Checking out 'ansible deployments' branch"
                sh 'git checkout ansible-k8s-deployments'
            }
        }
        stage('Deploy to Jetstreams') {
            environment {
                SSH_PRIVATE_KEY = credentials('ssh_key_ansible_to_k8s')
            }
            steps {
                sh 'pwd'
                script{
                    sh "ansible-playbook -i /etc/ansible-host-inventory playbooks/registry-playbook.yml --extra-vars \"version=$BUILD_NUMBER\" --private-key=$SSH_PRIVATE_KEY"
                }
            }
        }

    }
}