version: 'latest'
services:
  rabbitmq:
    container_name: rabbitmq_cont
    image: rabbitmq:3.9-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped # Remove incase of any unexpected behaviour.