pipeline {
    agent any
    
    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }
    environment {
        imagename = "cloudelves/gateway"
        dockerImage = ''
    }
    stages {
        stage('Cleanup') {
            steps {
                // Clean before build
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                echo "Checking out 'ci/gateway' branch"
                git branch: 'ci/gateway',
                url: 'https://github.com/airavata-courses/CloudElves.git',
                credentialsId: 'MyGitHub'
            }
        }
        // stage('Unit Test') {
        //     steps {
        //         /* Testing the application */
        //         echo 'Application Testing'
        //         dir('gateway') {
        //             sh "pwd"
        //             sh '//command to run the unit test for gateway'
        //         }
        //     }
        // }
        stage('Build Docker Image') {
             steps {
                dir('gateway') {
                    sh 'pwd'
                    sh 'mvnw clean package'
                    script {
                        dockerImage = docker.build imagename
                    }
                }   
            }
        }
         stage('Publish to DockerHub') {
            environment {
                registryCredential = 'dockerHub'
            }
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }
        stage('Remove unused docker image') {
            steps{
                sh "docker rmi $imagename:$BUILD_NUMBER"
                sh "docker rmi $imagename:latest"

            }
        }
        stage('Checkout ansible deployments branch') {
            steps {
                echo "Checking out 'ansible deployments' branch"
                sh 'git checkout ansible-k8s-deployments'
            }
        }
        stage('Deploy to Jetstreams') {
            environment {
                SSH_PRIVATE_KEY = credentials('ssh_key_ansible_to_k8s')
            }
            steps {
                sh 'pwd'
                script{
                    sh "ansible-playbook -i /etc/ansible-host-inventory playbooks/forecast-playbook.yml --extra-vars \"version=$BUILD_NUMBER\" --private-key=$SSH_PRIVATE_KEY"
                }
            }
        }

    }
}