pipeline {

    agent any
    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }
    environment {
        DOCKERHUB_CREDENTIALS='dockerHub'
        imagename="cloudelves/ui"
        dockerImage=''
    }
    stages {
        stage('Cleanup') {
            steps {
                // Clean before build
                cleanWs()
            }
        }
        stage('Checkout') {
            steps {
                echo "Checkout to Develop-ui"
                git branch: 'Develop-ui',
                url: 'https://github.com/airavata-courses/CloudElves',
                credentialsId: 'GitHub-Navkar'
            }
        }
        stage('Local Build') {
            steps {
                /* Installing application dependencies */
                echo "Building ${env.JOB_NAME}...."
                dir('forecast-ui/forecast-ui') {
                    sh "pwd"
                    sh 'npm install'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('forecast-ui') {
                    sh 'pwd'
                    script {
                    dockerImage = docker.build imagename
                    }
                }
                
            }
        }
         stage('Publish to DockerHub') {
            environment {
                registryCredential = 'dockerHub'
            }
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push("$BUILD_NUMBER")
                        dockerImage.push('latest')
                    }
                }
            }
        }
        stage('Remove unused docker image') {
            steps{
                sh "docker rmi $imagename:$BUILD_NUMBER"
                sh "docker rmi $imagename:latest"

            }
        }
         stage('Checkout ansible deployments branch') {
            steps {
                echo "Checking out 'ansible deployments' branch"
                sh 'git checkout ansible-k8s-deployments'
            }
        }
        stage('Deploy to Jetstreams') {
            environment {
                SSH_PRIVATE_KEY = credentials('ssh_key_ansible_to_k8s')
            }
            steps {
                sh 'pwd'
                script{
                    sh "ansible-playbook -i /etc/ansible-host-inventory playbooks/ui-playbook.yml --extra-vars \"version=$BUILD_NUMBER\" --private-key=$SSH_PRIVATE_KEY"
                }
            }
        }
    }
}