jobs:
  build:
    working_directory: ~/forecast
    docker:
      - image: "circleci/python:3.10.1"
    steps:
      - checkout
      - run: sudo pip3 install -r forecast/requirements.txt
      - run: python3 forecast/forecast/manage.py test
