spring:
  profiles:
    active: default, cloud

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8082

ingestor:
  host: localhost
  port: 8083
  serviceName: INGESTOR_SERVICE
  apiPath:
    getImage: /image

forecaster:
  host: forecaster
  port: 8001
  apiPath:
    forecast: /forecast
    storm: /stormclustering

registry:
  host: localhost
  port: 8080
  serviceName: local
  apiPath:
    getUser: /getUser?userId={userId}
    getAllUsers: /getUsers
    addUser: /addUser
    getEvents: /getEvents?userId={userId}
    getHistory: /getUserRequests?userId={userId}
    getRequestById: /getRequestById?id={id}

rmq:
  exchange: elvesExchange
  serviceName: local
  host: localhost
  port: 5672
  username: guest
  password: guest
  output:
    registry: elves.registry.applog.in
    userrequest: elves.registry.userrequest.in
    nexrad: elves.ingestor.nexrad.data.in
    mera: elves.ingestor.mera1.data.in

google:
  tokenUrl: https://oauth2.googleapis.com/tokeninfo?id_token={token}