springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8082

ingestor:
  host: ingestor
  port: 8000
  apiPath:
    getData: /getdata?year={year}&month={month}&day={day}&radar={radar}&id={id}&starttime={startTime}&endtime={endTime}
    getImage: /getimage

forecaster:
  host: forecaster
  port: 8001
  apiPath:
    forecast: /forecast
    storm: /stormclustering

registry:
  host: localhost
  port: 8080
  serviceName: REGISTRY_SERVICE
  apiPath:
    getUser: /getUser?userId={userId}
    getAllUsers: /getUsers
    addUser: /addUser
    getAppLog: /getAppLog?userId={userId}
    addAppLog: /addAppLog
    getLogById: /getLogs?id={id}
    getPlot: /getPlot?id={id}

rmq:
  exchange: elvesExchange
  serviceName: local
  host: 149.165.157.38
  port: 30006
  username: guest
  password: guest
  output:
    registry: elves.registry.eventlog.in
    ingestor: elves.ingestor.data.in

google:
  tokenUrl: https://oauth2.googleapis.com/tokeninfo?id_token={token}