apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db-secret
    namespace: keycloak
stringData:
    POSTGRES_DATABASE: postgresDB
    POSTGRES_EXTERNAL_ADDRESS: keycloak-db-postgresql.keycloak.svc.cluster.local
    POSTGRES_EXTERNAL_PORT: "5432"
    POSTGRES_PASSWORD: pg-password
    POSTGRES_SUPERUSER: "true"
    POSTGRES_USERNAME: pg-usernmae
type: Opaque
