kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry
  namespace: elves
spec:
  replicas: 1
  selector:
    matchLabels:
      run: registry
      app: registry
  template:
    metadata:
      labels:
        run: registry
        app: registry
    spec:
      containers:
        - name: registry
          image: docker.io/madhavankr/elves-registry:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: server.port
            value: "8080"
          - name: spring.rabbitmq.host
            value: mu-rabbit-rabbitmq.elves.svc
          - name: spring.rabbitmq.port
            value: "5672"
          - name: spring.rabbitmq.username
            value: "user"
          - name: db.host
            value: postgres-postgresql.elves.svc.cluster.local
          - name: db.port
            value: "5432"
          - name: spring.rabbitmq.password
            valueFrom:
              secretKeyRef:
                name: mu-rabbit-rabbitmq
                key: rabbitmq-password
          - name: db.password
            valueFrom:
              secretKeyRef:
                name: postgres-postgresql
                key: postgres-password

          ports:
          - name: registry
            containerPort: 8080
            protocol: TCP
