server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  profiles:
    active: cloud

db:
  host: localhost
  port: 5000
  username: postgres
  password: O0T1qpeyKd
  name: postgres

#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: elves
#    password: cloudelves

rmq:
  serviceName: local
  host: localhost
  port: 5672
  username: guest
  password: guest
  consumerCount: 10
  exchange: elvesExchange
  input:
    applog: elves.registry.applog.in
    userdetails: elves.registry.userdetails.in
    ingestor: elves.registry.ingestor.in
