server:
  port: 8080

db:
  host: localhost
  port: 5000
  username: postgres
  password: cloudelves
  name: postgres

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: elves
    password: cloudelves

rmq:
  consumerCount: 10
  exchange: elvesExchange
  input:
    applog: elves.registry.applog.in
    userdetails: elves.registry.userdetails.in
    ingestor: elves.registry.ingestor.in
